# Generated by Django 6.0 on 2026-01-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otp_options_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='bank_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='ifsc_code',
            field=models.CharField(max_length=20),
        ),
    ]
